# Generated by Django 3.2.9 on 2021-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
