# Generated by Django 3.2.9 on 2021-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='personas.Habilidades'),
        ),
    ]
