# Generated by Django 3.2.9 on 2021-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'TÉCNICO'), ('1', 'DIRECCIÓN'), ('2', 'ASISTENTE DE DIRECCIÓN'), ('3', 'ASISTENTE CONTABLE'), ('4', 'COORDINACIÓN ACADÉMICA'), ('5', 'BIBLIOTECA')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
