# Generated by Django 3.2.9 on 2021-12-07 20:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='Texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'TÉCNICO'), ('1', 'DIRECCIÓN'), ('2', 'ASISTENTE DE DIRECCIÓN'), ('3', 'ASISTENTE CONTABLE'), ('4', 'COORDINACIÓN ACADÉMICA'), ('5', 'BIBLIOTECA')], max_length=1, verbose_name='Puesto de trabajo'),
        ),
    ]
