# Generated by Django 3.2.9 on 2021-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20211207_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades', 'verbose_name_plural': 'Habilidades de empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'TÉCNICO'), ('1', 'DIRECCIÓN'), ('2', 'ASISTENTE DE DIRECCIÓN'), ('3', 'ASISTENTE CONTABLE'), ('4', 'COORDINACIÓN ACADÉMICA'), ('5', 'BIBLIOTECA'), ('6', 'SERVICIO'), ('7', 'CONTADOR GENERAL'), ('8', 'JEFE'), ('9', 'JEFA')], max_length=1, verbose_name='Puesto de trabajo'),
        ),
    ]
