# Generated by Django 3.2.9 on 2021-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20211210_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='empleado'),
        ),
    ]
